import React, { useState } from 'react'
import { Table, Space, Button, Card, Modal } from 'antd'


export default function Dash() {

  const [dataSource, setDataSource] = useState([
    {
      "id": 1,
      "name": "administrador",
      "email": "admin@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$CZ4RL1Rit7EEY5xrDbTQUOdQA//rcQnpiNOBfKXmN/wTBFLDUxBAK",
      "remember_token": null,
      "role_id": "1",
      "id_sucursal": 0,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "4432170690",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 2,
      "name": "RICARDO FLORES VALADEZ",
      "email": "FOVR730718MG6@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$7HR7ZwrQV.c.eVpMWTnkDuq8AfEnaY2eytwPXAlvbwnJgPgn4qPay",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 1,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 3,
      "name": "HECTOR ZARATE DAGIO",
      "email": "ZADH760915475@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$GbT1zURWDmy0oeAStc2heu1ZSe/xHJ39eG5iOUu0mbbSgUejcNOra",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 2,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 4,
      "name": "JOSE ALEJANDRO ARROYO VEGA",
      "email": "AOVA710607A5A@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$1xK.JDK8tLLLyR8OWiFQCOI61Jmf.fpXCaVOhYU1onNlqBY2FAf3K",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 3,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 5,
      "name": "JULIO CESAR CALDERON RAMOS",
      "email": "CARJ771128SA1@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$2V83SHKLLZOyaAl6EPdgAedcOu7cL4ej94gMOxJlVxh1PwhDp.tM2",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 4,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 6,
      "name": "CUEVAS MENDOZA GLENDA MICHEL",
      "email": "CUMG7610013V8@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$j1rnDL0tIUe.WbCc4UrxQe8qCyERbk1B49CPE8qcsh9cbrMZID6uG",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 5,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 7,
      "name": "CONSORCIO SERV ADMINISTRATIVOS BIENES RAICES GUILLERMO AMOR VAZQUEZ, S.A. DE C.V.",
      "email": "CSA840228KG4@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$AukRqKQ0X4WEGQiibc5p8.7xHB0EYJG4IPHmcBJ2bEx5578HLaDDC",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 6,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 8,
      "name": "GUILLERMO MIGUEL AMOR VAZQUEZ",
      "email": "AOVG420626291@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$BLIFqSu8.hjgSxDDv0rHseHcydQX01TJY0MxUFZHJY97ylOr73rVu",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 7,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 9,
      "name": "CHRISTIAN RINCON RENTERIA",
      "email": "RIRC8307251F1@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$4m7PQXfaet3LiTWVEAoE2ub54NilCRuy22ZYvrmTE9OrlZCBxnJwC",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 8,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 10,
      "name": "DENTAL MEDIC, S.C.",
      "email": "DME071214EJ4@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$uyN97rGhQcJ.vjsoyuKxjefaGlu7akCXShAEQW2pPiNxpNW2tL6m.",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 9,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 11,
      "name": "ANA MARIA PEREZ ROMERO",
      "email": "PERA6302072H6@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$RL9Ms5Y0e9Fnn1WI2OWVG./KKOOBOEH8Zl70T7fRapqltwT1Oxz/S",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 10,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 12,
      "name": "Bryant Dylan León Durán",
      "email": "LE\\DB890215TF6@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$OlqfGgXgAjuhomLG7MYYxOaLcYzf9mWtwDdrHxeccHHcgoHXBtmPi",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 11,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 13,
      "name": "SALVADOR AMBRIZ BANDERAS",
      "email": "AIBS830223J88@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$1pL8zwUhBNZ1rBdrXpF77eJwOyuoEby5CgB8ysy2yyqJio7JOzVn.",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 12,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 14,
      "name": "SANDRA GARCIA ORTIZ 4",
      "email": "GAOS841130F91@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$9hbcfTx41/f7gF4zFBT1bOr6mkw0lmVYbhE1lo4ESjH4S.aQZBPWO",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 13,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 15,
      "name": "MARCO ANTONIO ARIAS CHAVEZ",
      "email": "AICM8002245N0@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$UtJ9JXReWmZK42n4xXLzjOVatQ5YyU2lz25OI8JgnzmOGBYAdFcXW",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 14,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 16,
      "name": "MARIA VICTORIA ROMERO SOTELO",
      "email": "ROSV730728779@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$N8arxjuNRy9uprt6mEIqCeznfh0PAvWnSzAOcDoNNte8dBHJEk8l.",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 15,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 17,
      "name": "JUAN MANUEL GINORI COLO",
      "email": "GICJ600616GT6@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$Y0wbf1J1hjR9ckubxkKl2.IJ7dzhU5XiO0NuUh0CYg8eTM7BHu6ta",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 16,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 18,
      "name": "MA MERCEDES GONZALEZ VALVERDE",
      "email": "GOVM630321PN6@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$4UWDpJLXK9xlIm4q.Y9qz.fwEyvk92pd1efhbDSndY65ajA7Upnvu",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 17,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 19,
      "name": "F T INMOBILIARIA S.A. DE C.V.",
      "email": "FTI0107306X9@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$pZ6ynsXuv7vSbYudKT4HEeAxbwPX4owBE2ac78bWC9Bi4Pir/qMYa",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 18,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 20,
      "name": "ALEJANDRO CONSTANTINO HERNANDEZ",
      "email": "COHA710820AY7@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$7BL5yiuawlehKLulvleWkeVbx7.ttlG0gz5SdwBIIUggxFdKzKtqO",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 19,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 21,
      "name": "MARTHA DELFINA CERVANTES CARREÑO",
      "email": "CECM640727498@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$XT3zWkJ44YVii6OU4bRt5OHg17O5XhU3Z4MbnsZgnPk4VB.oGAKRa",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 20,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 22,
      "name": "GONZALO BARAJAS CORTES",
      "email": "BACG580109HH1@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$Gdw0zKiwCPpcxLZ4gzPrTOIGJf7Cd5IG2QICHg/icCvGtKXGgMY92",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 21,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 23,
      "name": "NAIZETH LIRA CORDOBA",
      "email": "LICN811117HV8@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$KgV.qp7Ab2d.7wyMmTvwjObHbX9qVZhYBT8rwmK45RtL67M2w2wwS",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 22,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 24,
      "name": "GUADALUPE SANCHEZ BADILLO",
      "email": "SABG840420GB4@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$CjgqUlHeZjLnjkA5zZm1Xea1lP/7BORKqWMZ2fFYUXXw10SW3FUX.",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 23,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 25,
      "name": "JESUS PRIETO CORDERO",
      "email": "PICJ851114QZ2@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$6gd6iCdCkT1W7XDgsoyaWOUcywqba0U/k1xeuejLdX9HU/RjSqkLW",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 24,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 26,
      "name": "RUBEN CRUZ CORDERO BARBERENA",
      "email": "COBR500503AD1@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$LuBgPs9FihCC4Z/Pyjz4kefTf33/ntap5NfrOh.OlizxPdZc0kO3e",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 25,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 27,
      "name": "JOSE ANTONIO MARTINEZ ALBA",
      "email": "MAAA6301155N6@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$UKqG/e665Ay1Y33fvalieuPVS6jdi9WupH93Zxn1FhfV4GzcZANqS",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 26,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 28,
      "name": "MYRNA REBECA MARTINEZ JIMENEZ ",
      "email": "MAJM5706049LA@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$Lne5h3nHIhgDfKBWrx3szOcSycHTwyArGTEYW2BtMo9.W0A8qxuDm",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 27,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 29,
      "name": "BEATRIZ GAMBOA ALARCON ",
      "email": "GAAB6808047Q9@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$W9kPw7erQkB0yfSsDMGonuKJmkWwun/9bxLaVNcJufixvUjv.iiJm",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 28,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 30,
      "name": "ELVIRA ESPINOZA ESPINOZA",
      "email": "EIEE7503258Q3@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$LQoz9bhb7/ZhL1kuiwNJmO4aJCIZMERwgY7b1xBQpTmmBkRd0I8I.",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 29,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 31,
      "name": "EDGAR",
      "email": "edgar@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$NMeok78HnlrwPG77vIiF/OrBSBJsZFfdgsnNWMKGK7d1SjtqXA0x.",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 30,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 32,
      "name": "JOSE CALIXTO GARCIA BUCIO",
      "email": "calixtogarciabucio@gmail.com",
      "email_verified_at": null,
      "password": "$2y$10$Hst5LFXlxqvY/Zja2fs5Hem3SQf4qXMgS/jy8lx31tDH6B.PBadeK",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 31,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 33,
      "name": "OSCAR CARRANZA",
      "email": "oscarranzab@yahoo.com.mx",
      "email_verified_at": null,
      "password": "$2y$10$U2zfeU9xMmCK0CanfGNo5.59XDCecE88Rub6cUb8KNCw2v2wNM1Oi",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 32,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 34,
      "name": "PAULO VARGAS",
      "email": "dr_enriquevargasm@yahoo.com.mx",
      "email_verified_at": null,
      "password": "$2y$10$OU2tebHxRBBK8P2qDLmcb.q3sRFpG6RhK9clRWAjXFCpEovHVex8q",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 33,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 35,
      "name": "MISAEL TAPIA OROZCO",
      "email": "misaeltapiao@yahoo.com",
      "email_verified_at": null,
      "password": "$2y$10$XLkwI29biJl5.OfW71iJwuY4WgR18zidAgKzg1eo.GoA0bhCovNVq",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 34,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 36,
      "name": "EMILIO ANGUIANO",
      "email": "emilio.anguiano@gmail.com",
      "email_verified_at": null,
      "password": "$2y$10$WAlmh5T5bQVw1ibCNlaqyuMyrbtCjaj/6AcBbnu5r8/v3rRful196",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 35,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 37,
      "name": "DRA. GUADALUPE ZAMUDIO HERNANDEZ",
      "email": "zamudio@clinicawh.com",
      "email_verified_at": null,
      "password": "$2y$10$SiSKNL92nL7dWOV9/sSRpedb22eQSrYnS5jxvInePQDDEIbITPQnu",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 36,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 38,
      "name": "ANDREA PORTILLO",
      "email": "andyport_81@hotmail.com",
      "email_verified_at": null,
      "password": "$2y$10$OJziE7/mAWzQ6SD1FDPm/uNX1zl3NO1vLy8rGVBvCznL/QqVKvIpC",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 37,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 39,
      "name": "ALDO CABALLERO",
      "email": "aldo0891@hotmail.com",
      "email_verified_at": null,
      "password": "$2y$10$RlfYoI7/6Wg/KmoAo.I6Z.kVzcv359/QWeIRk2TpyQxWHvoPOMWLy",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 38,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 40,
      "name": "recepcionista",
      "email": "recepcionista@recreamed.com",
      "email_verified_at": null,
      "password": "$2y$10$0hwO8ncAkU1pr4OTHS949OQazLxh.0TO4QD5MdHwexi9Xlp0LakJe",
      "remember_token": null,
      "role_id": "3",
      "id_sucursal": 1,
      "id_medicoasignado": 0,
      "avatar": "logo-avatar.png",
      "telefono": "4432170690",
      "cedula": "00000000",
      "numinterior": "",
      "numexterior": "",
      "calle": "",
      "colonia": "",
      "municipio": "",
      "estado": "",
      "codigopostal": "",
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 41,
      "name": "huhu",
      "email": "ajsdasd2@asdasd.com",
      "email_verified_at": null,
      "password": "qwerty",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 1,
      "id_medicoasignado": 1,
      "avatar": "",
      "telefono": null,
      "cedula": null,
      "numinterior": null,
      "numexterior": null,
      "calle": null,
      "colonia": null,
      "municipio": null,
      "estado": null,
      "codigopostal": null,
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": "2022-02-09 20:08:39",
      "updated_at": "2022-02-09 20:08:39"
    },
    {
      "id": 42,
      "name": "Gildardo",
      "email": "amatias@recreamed.com",
      "email_verified_at": null,
      "password": "abcd1234",
      "remember_token": null,
      "role_id": "2",
      "id_sucursal": 1,
      "id_medicoasignado": 1,
      "avatar": "",
      "telefono": null,
      "cedula": null,
      "numinterior": null,
      "numexterior": null,
      "calle": null,
      "colonia": null,
      "municipio": null,
      "estado": null,
      "codigopostal": null,
      "certificacion": null,
      "universidad": null,
      "estatus": 0,
      "created_at": "2022-02-09 20:55:13",
      "updated_at": "2022-02-09 20:55:13"
    }
  ])

  const [usuario, setUsuario] = useState({});
  const [isModalVisible, setIsModalVisible] = useState(false);
  const showModal = () => { setIsModalVisible(true); };
  const handleOk = () => { setIsModalVisible(false); };
  const handleCancel = () => { setIsModalVisible(false); };

  const columns = [
    {
      title: 'Nombre',
      dataIndex: 'name',
      key: 'name',
    },
    {
      title: 'Rol',
      dataIndex: 'role_id',
      key: 'rol',
    },
    {
      title: 'Sucursal',
      dataIndex: 'id_sucursal',
      key: 'address',
    },
    {
      title: 'Telefono',
      dataIndex: 'telefono',
      key: 'tel',
    },
    {
      title: 'Detalles',
      key: 'detalles',
      render: (text, record) => (
        <Space size="middle">
          <Button onClick={()=>{setUsuario(record); showModal();}}>Detalles</Button>
        </Space>
      )
    }
  ];

  const gridStyle = {
    width: '50%',
    height: '50px',
    textAlign: 'center',
    display: 'inline-flex',
    justifyContent: 'center',
    alignItems: 'center'
  };

  function DetalleUsuario() {
    return <div>
      <Card bordered={false}>
        {
          Object.keys(usuario).map(k => {
            return <><Card.Grid style={gridStyle}>{k}</Card.Grid><Card.Grid style={gridStyle} size='small'>{usuario[k]}</Card.Grid></>
          })
        }
      </Card>
    </div>
  }

  return (
    <div>
      <h4>Usuarios</h4>
      <Table dataSource={dataSource} columns={columns} />
      <Modal width={800} title={<h4>Detalles de la nota </h4>} visible={isModalVisible} onOk={handleOk} onCancel={handleCancel}>
        <DetalleUsuario />
      </Modal>
    </div>
  )

}
